spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/java?useUnicode=ture&charachterEncoding=UTF-8
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
    timeout: 0
    lettuce:
      pool:
        enabled: true
